### ISSUE TITLE
Metadata not set for members that join whilst already in the membership list

### ISSUE THREAD

**Issue by manuelbernhardt** [lalithsuresh/rapid#16]
It is possible for members to issue two phase 2 join requests if the response to the first one timed out (but was successfully processed nonetheless). In that case the seed will reply with a configuration id of `-1`, prompting the client to fetch the list. In this case, the metadata isn't sent along with the list of members.

See [this commit](https://github.com/manuelbernhardt/rapid/commit/8bbf9fc555a674f0ebc25cadfa155c76def2f965#diff-0f981d5423e5624e3ddb8cb7bd8e8553R272) which appears to fix the issue. Please disregard the changes to the tests as those do not appear to be working (I tried to simulate the scenario but the way I went about it doesn't appear to work)

**Comment by lalithsuresh** [comment]
Great catch! Thank you. If you send me a commit with just the change to MembershipService, I'll merge it.

**Comment by lalithsuresh** [comment]
Fixed by https://github.com/lalithsuresh/rapid/commit/ef455886be5d43d049af188d2b19cb4f02486abe
